[workspace]
members = [
    "compiler/llvm",
    "compiler/util",
    "compiler/lexer",
    "compiler/parser",
    "compiler/compiler",
    "compiler/cli",
    "compiler/check",
    "compiler/main",
]